[package]
name = "drgdfu"
version = "0.1.0"
authors = ["Ulf Lilleengen <lulf@redhat.com>"]
edition = "2021"
description = "A DFU update tool for Drogue Device's with DFU capabilities"

[dependencies]

uuid = { version = "0.8", features = ["v4"] }
clap = { version = "3.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
bluer = "0.13"
tokio = { version = "1", features = ["full"] }
log = "0.4.11"
chrono = "0.4"
bytes = "1.1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
stderrlog = "0.4"
futures = "0.3"
anyhow = "1.0"
humantime = "2"

[features]
default = []
