name: CI
on:
  push:
    branches: [staging, trying, main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Add dependencies
        run: |
          sudo apt-get update; DEBIAN_FRONTEND="noninteractive" sudo apt-get -y install build-essential curl tzdata libdbus-1-dev pkg-config
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
